data:
  dataset: "../data/test_datasets/ixi_train.json"
  data_dir: "../data/test_datasets/ixi"
  batch_size: 24
  img_size:
    - 256
    - 256
  skull_strip: true
  num_workers: 24
  slice_thickness: 1
  cache: "processes"
  target_sequence: "t2"
  guidance_sequences:
    - "t1"
    - "pd"
  subset_train: null
  subset_val: null